# Generated by Django 4.1.4 on 2023-01-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HyliApp', '0002_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
