# Generated by Django 4.1.4 on 2023-01-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HyliApp', '0003_news_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='news_photo'),
        ),
    ]
